/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-08-26 15:30:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.ab.models.Book;
import com.ab.models.Basket;

public final class view_005fbasket_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/java%20programming%20tools/new%20workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/online-book-store-application/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153381482000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1660819643593L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.ab.models.Basket");
    _jspx_imports_classes.add("com.ab.models.Book");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>view books</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {margin: 0;\r\n");
      out.write(" background: rgba(0, 128, 0, 0.3);}\r\n");
      out.write(" \r\n");
      out.write(" h1{\r\n");
      out.write(" text-align: center;\r\n");
      out.write("  padding-top: 50px;\r\n");
      out.write(" \r\n");
      out.write(" }\r\n");
      out.write(" letter {\r\n");
      out.write("   color: #ea503f;\r\n");
      out.write("   font-family: Arial;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("ul.topnav {\r\n");
      out.write("  list-style-type: none;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  background-color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.topnav li {float: left;}\r\n");
      out.write("\r\n");
      out.write("ul.topnav li a {\r\n");
      out.write("  display: block;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 14px 16px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.topnav li a:hover:not(.active) {background-color: #111;}\r\n");
      out.write("\r\n");
      out.write("ul.topnav li a.active {background-color: #04AA6D;}\r\n");
      out.write("\r\n");
      out.write("ul.topnav li.right {float: right;}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 600px) {\r\n");
      out.write("  ul.topnav li.right, \r\n");
      out.write("  ul.topnav li {float: none;}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("<ul class=\"topnav\">\r\n");
      out.write("  <li><a class=\"active\" href=\"welcome.jsp\">Home</a></li>\r\n");
      out.write("  <li><a href=\"http://localhost:8080/online-book-store-application/ViewBookServlet\">View Available Books</a></li>\r\n");
      out.write("  <li><a href=\"search_book.jsp\">Search Books</a></li>\r\n");
      out.write("  <li><a href=\"http://localhost:8080/online-book-store-application/BasketViewServlet\">View Basket</a></li>\r\n");
      out.write("  <li><a href=\"login.jsp\">Checkout</a></li>\r\n");
      out.write("  <li class=\"right\"><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("  <li class=\"right\"><a href=\"index.jsp\">Sign Up</a></li> \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"http://localhost:8080/online-book-store-application/BasketViewServlet\"  method=\"GET\">\r\n");

Basket b =(Basket)session.getAttribute("addBook");


      out.write(" \r\n");
      out.write("<div class=\"letter\"><h1>Book Added to Basket</h1></div>\r\n");
      out.write("<center>\r\n");
      out.write("<br>\r\n");
      out.write("<table border=\"4\" style=\"width:30%\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <th>Title</th>\r\n");
      out.write("    <th>$ Price</th>\r\n");
      out.write("  </tr>\r\n");
      out.write("        <tr style = \"text-align :center \">\r\n");
      out.write("            <td><a>");
      out.print(b.getBookTitle());
      out.write("</a></td>\r\n");
      out.write("            <td><a>");
      out.print(b.getBookPrice());
      out.write("</a></td>\r\n");
      out.write("            <td> <form action=\"http://localhost:8080/online-book-store-application/BasketViewServlet\" method=\"GET\"> \r\n");
      out.write("            <input type=\"submit\" value=\"View Basket\"/>\r\n");
      out.write(" </form>  \r\n");
      out.write(" </td> \r\n");
      out.write("      </tr>    \r\n");
      out.write(" </form>\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("</center>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
